/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev` or `next build`.
// It is committed here so the project type-checks immediately after
// `npm install` without needing a first build pass.
